name: Codespaces Prebuild

on:
  push:
    branches: [ main, containerize ]
  workflow_dispatch:

jobs:
  prebuild:
    name: Create Codespaces Prebuild
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup GitHub Codespaces prebuild
        uses: github/codespaces-precache@v1
        with:
          regions: WestUs2
          retention-days: 30
